#!/bin/bash

sbatch run/della/dddas/car/0520/car_experiment_predict_x0_violation_schedule_NA_normalize_direct_clip_max_sample_500_weight_0001_seed_1.slurm
sbatch run/della/dddas/car/0520/car_experiment_predict_x0_violation_schedule_NA_normalize_direct_clip_max_sample_500_weight_0001_seed_2.slurm
