#!/bin/bash

sbatch run/della/dddas/tabletop/0511/tabletopv2_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_100_weight_1_seed_0.slurm
sbatch run/della/dddas/tabletop/0511/tabletopv2_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_100_weight_1_seed_1.slurm
sbatch run/della/dddas/tabletop/0511/tabletopv2_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_100_weight_1_seed_2.slurm
sbatch run/della/dddas/tabletop/0511/tabletopv2_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_500_weight_01_seed_0.slurm
sbatch run/della/dddas/tabletop/0511/tabletopv2_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_500_weight_01_seed_1.slurm
sbatch run/della/dddas/tabletop/0511/tabletopv2_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_500_weight_01_seed_2.slurm
