#!/bin/bash

sbatch run/della/dddas/car/0507/car_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_100_weight_1_seed_1.slurm
sbatch run/della/dddas/car/0507/car_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_100_weight_1_seed_2.slurm
sbatch run/della/dddas/car/0507/car_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_500_weight_01_seed_1.slurm
sbatch run/della/dddas/car/0507/car_experiment_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_500_weight_01_seed_2.slurm
sbatch run/della/dddas/car/0507/car_experiment_predict_x0_violation_schedule_NA_normalize_direct_clip_max_sample_100_weight_001_seed_1.slurm
sbatch run/della/dddas/car/0507/car_experiment_predict_x0_violation_schedule_NA_normalize_direct_clip_max_sample_100_weight_001_seed_2.slurm
sbatch run/della/dddas/car/0507/car_experiment_predict_x0_violation_schedule_one_over_t_normalize_direct_clip_max_sample_500_weight_01_seed_1.slurm
sbatch run/della/dddas/car/0507/car_experiment_predict_x0_violation_schedule_one_over_t_normalize_direct_clip_max_sample_500_weight_01_seed_2.slurm
