#!/bin/bash

sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_gt_scaled_schedule_NA_normalize_-1_-1_var_max_sample_100_weight_1_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_gt_scaled_schedule_NA_normalize_-1_-1_var_max_sample_500_weight_01_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_gt_scaled_schedule_NA_normalize_direct_clip_max_sample_100_weight_1_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_gt_scaled_schedule_one_over_t_normalize_-1_-1_var_max_sample_500_weight_10_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_gt_scaled_schedule_one_over_t_normalize_direct_clip_max_sample_500_weight_10_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_gt_scaled_schedule_sqrt_bar_alpha_normalize_-1_-1_var_max_sample_500_weight_1_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_gt_scaled_schedule_sqrt_bar_alpha_normalize_direct_clip_max_sample_500_weight_1_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_predict_x0_violation_schedule_NA_normalize_direct_clip_max_sample_100_weight_001_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_vanilla_schedule_NA_normalize_-1_-1_var_max_sample_100_weight_001_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_vanilla_schedule_NA_normalize_direct_clip_max_sample_100_weight_001_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_vanilla_schedule_one_over_t_normalize_-1_-1_var_max_sample_500_weight_01_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_vanilla_schedule_sqrt_bar_alpha_normalize_-1_-1_var_max_sample_500_weight_0001_seed_0.slurm
sbatch run/della/dddas/tabletop/0429/tabletopv2_constraint_vanilla_schedule_sqrt_bar_alpha_normalize_direct_clip_max_sample_500_weight_0001_seed_0.slurm
