#!/bin/bash

sbatch run/della/dddas/tabletop/0520/tabletopv2_experiment_pred_x0_schedule_NA_normalize_direct_clip_max_sample_500_weight_001_seed_1.slurm
sbatch run/della/dddas/tabletop/0520/tabletopv2_experiment_pred_x0_schedule_NA_normalize_direct_clip_max_sample_500_weight_001_seed_2.slurm
